export const MAP_STOPS = [
  {
    id: 'start',
    kind: 'start',
    label: 'Lobby',
    icon: '🏠',
    time: 'Estreia (31/Jul)',
    hint: 'Estreia e perfil',
  },
  {
    id: 'd1',
    kind: 'day',
    gameDay: 1,
    label: 'Dia 1',
    title: 'Dia 1 · Rodadas 2-4',
    icon: '✨',
    time: '1 de Agosto',
    hint: 'Competição inicial no hotel',
  },
  {
    id: 'd2',
    kind: 'day',
    gameDay: 2,
    label: 'Dia 2',
    title: 'Dia 2 · Rodadas 5-7',
    icon: '🪙',
    time: '2 de Agosto',
    hint: 'Desafios de câmbios e wireds',
  },
  {
    id: 'd3',
    kind: 'day',
    gameDay: 3,
    label: 'Dia 3',
    title: 'Dia 3 · Rodadas 8-10',
    icon: '🔑',
    time: '3 de Agosto',
    hint: 'Segredos e console do hotel',
  },
  {
    id: 'd4',
    kind: 'day',
    gameDay: 4,
    label: 'Dia 4',
    title: 'Dia 4 · Rodadas 11-13',
    icon: '👑',
    time: '4 de Agosto',
    hint: 'Tratamento VIP e visual',
  },
  {
    id: 'd5',
    kind: 'day',
    gameDay: 5,
    label: 'Dia 5',
    title: 'Dia 5 · Rodadas 14-16',
    icon: '⚡',
    time: '5 de Agosto',
    hint: 'Química e giro da sorte',
  },
  {
    id: 'd6',
    kind: 'day',
    gameDay: 6,
    label: 'Dia 6',
    title: 'Dia 6 · Rodadas 17-19',
    icon: '🔮',
    time: '6 de Agosto',
    hint: 'Decisões dramáticas de date',
  },
  {
    id: 'd7',
    kind: 'day',
    gameDay: 7,
    label: 'Dia 7',
    title: 'Dia 7 · Rodadas 20-22',
    icon: '🏆',
    time: '7 de Agosto',
    hint: 'Reta final e apuração de votos',
  },
  {
    id: 'treasure',
    kind: 'treasure',
    label: 'Final',
    icon: '💎',
    time: 'Grande Final (8/Ago)',
    hint: 'Premiação Geral Ouro e matches',
  },
]

export const TOTAL_ROUNDS = 22
